export const sampleDishes = [
  {
    id: 1,
    title: "Spaghetti Carbonara",
    price: 12.99,
    imageUrl: "/food/carbonara.jpg",
    category: "Plat Principal",
  },
  {
    id: 2,
    title: "Pizza Margherita",
    price: 10.99,
    imageUrl: "/food/margherita.jpg",
    category: "Plat Principal",
  },
  {
    id: 3,
    title: "Salade César",
    price: 8.99,
    imageUrl: "/food/caesar.jpg",
    category: "Entrée",
  },
  {
    id: 4,
    title: "Saumon Grillé",
    price: 15.99,
    imageUrl: "/food/salmon.jpg",
    category: "Plat Principal",
  },
  {
    id: 5,
    title: "Tacos de Boeuf",
    price: 9.99,
    imageUrl: "/food/tacos.jpg",
    category: "Plat Principal",
  },
  {
    id: 6,
    title: "Curry de Poulet",
    price: 11.99,
    imageUrl: "/food/curry.jpg",
    category: "Plat Principal",
  },
  {
    id: 7,
    title: "Plateau de Sushi",
    price: 18.99,
    imageUrl: "/food/sushi.jpg",
    category: "Plat Principal",
  },
  {
    id: 8,
    title: "Pad Thaï",
    price: 13.99,
    imageUrl: "/food/padthai.jpg",
    category: "Plat Principal",
  },
  {
    id: 9,
    title: "Cheeseburger",
    price: 10.49,
    imageUrl: "/food/cheeseburger.jpg",
    category: "Plat Principal",
  },
  {
    id: 10,
    title: "Sauté de Légumes",
    price: 9.49,
    imageUrl: "/food/stirfry.jpg",
    category: "Plat Principal",
  },
  {
    id: 11,
    title: "Gyro d'Agneau",
    price: 12.49,
    imageUrl: "/food/gyro.jpg",
    category: "Plat Principal",
  },
  {
    id: 12,
    title: "Gâteau au Chocolat",
    price: 6.99,
    imageUrl: "/food/cake.jpg",
    category: "Dessert",
  },
  {
    id: 13,
    title: "Tiramisu",
    price: 7.99,
    imageUrl: "/food/tiramisu.jpg",
    category: "Dessert",
  },
  {
    id: 14,
    title: "Tarte aux Pommes",
    price: 5.99,
    imageUrl: "/food/applepie.jpg",
    category: "Dessert",
  },
  {
    id: 15,
    title: "Coupe Glacée",
    price: 4.99,
    imageUrl: "/food/sundae.jpg",
    category: "Dessert",
  },
  {
    id: 16,
    title: "Panna Cotta",
    price: 6.49,
    imageUrl: "/food/pannacotta.jpg",
    category: "Dessert",
  },
  {
    id: 17,
    title: "Coca Cola",
    price: 1.99,
    imageUrl: "/food/cocacola.jpg",
    category: "Boisson",
  },
  {
    id: 18,
    title: "Jus d'Orange",
    price: 2.99,
    imageUrl: "/food/orangejuice.jpg",
    category: "Boisson",
  },
  {
    id: 19,
    title: "Limonade",
    price: 2.49,
    imageUrl: "/food/lemonade.jpg",
    category: "Boisson",
  },
  {
    id: 20,
    title: "Eau Minérale",
    price: 1.49,
    imageUrl: "/food/water.jpg",
    category: "Boisson",
  },
];
